server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://claribel.csxzvtikrxqk.us-east-2.rds.amazonaws.com:3306/master_db?rewriteBatchedStatements=true
    username: ocs_dev_owner
    password: Secure$!ocs_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      show_sql: true
      format_sql: true
      ddl-auto: update
spring.jpa.properties.hibernate.jdbc.batch_size: 1000
spring.jpa.properties.hibernate.order_inserts: true
spring.jpa.properties.hibernate.order_updates: true
spring.jpa.properties.hibernate.generate_statistics: true